### ISSUE TITLE
Improved configuration/runtime (`.aocbench.yaml`) support

### ISSUE THREAD

**Issue by ShaneMcC** [ShaneMcC/AoCBench#17]
Originally participants were expected to provide scripts/dockerfiles in their repos that aocbench would naively run and hope provided the required output.

This is problematic for a number of reasons:
1) Any repo could run anything on the benchmarking host, there was no real validation of what `run.sh` did
2) This required a lot of additional pollution in repos to make them compatible
3) How things behaved and was benchmarked was mostly a best-effort gentleman's agreement between participants to all use `bash` and `time` and run things in a specific way
   A) Compiled languages often had extra pain to decide when they should/shouldn't compile and often ended up just recompiling every single run
4) Adding support for alternative methods of benchmarking (`hyperfine`) was basically impossible as it would need all participants to update their run scripts

Instead, repos should add a single `.aocbench.yaml` file that defines how to run the code, `aocbench` itself shoudl then handle building/maintaining/running appropriate docker containers and then running the code inside the container to actually do tasks such as compiling, validation of output, benchmarking.

To allow for generic containers to be used, we should provide our own static-compiled versions of any of our requirements such as `bash` and `hyperfine`

**Comment by ShaneMcC** [comment]
This has been added and running successfully for a while.

Documentation still needs updated for this once all the kinds are worked out.
Old-style (V1) participants should be deprecated.

Example:

```yaml
### .aocbench.yaml version
### Default: none - This must be specified as 1.
version: 1

### Repo Author
### Default: none
author: Dataforce

### Language used
### Default: none
language: PHP

### Optional version prefix, changing this will invalidate all previous runs without needing to make
### other code changes.
### Default: none
# versionprefix: 1

### Path to Dockerfile to build image
### The image will be rebuilt if this file changes.
### This should just produce an environment that can compile/run the code
### (and can be reused every day), it should not compile the code itself
### Default: none - Must be specified if image is not.
dockerfile: docker/Dockerfile

### Or image (this takes priority, same idea as above)
### Default: none - Must be specified if dockerfile is not.
# image: php:8.3-cli

### Location where repo checkout should be mounted
### Default: /code
code: /code

### [%] Additional directories that need persisting across container runs.
### Separate container instances are created each time we run commands.
### Anything not included here will be lost across runs.
### The code directory is automatically persisted.
### Default: none
persistence:
 - /tmp

### [%] What directory to run commands from.
### Default: the value of the `code` setting
workdir: /code/%day%

### [%] Before benchmarking, command to run once to build a given day if needed.
### This runs once in a separate container instance than the regular code runs.
### This will always be run at least once before the cmd for the day is run.
### Default: none
runonce: /code/docker/build.sh %day%

### [%] When running image, command to run before the benchmarking occurs.
### This runs once in the same container instance as the regular code runs and gets run every time the code is run
### This should not be used for slow/time-consuming jobs such as compiling, and is mostly tweaking the environment if needed
### Default: none
prerun: /code/docker/enableJit.sh

### [%] When running image, command to run a given day, this is passed to `hyperfine` or `time` to actually benchmark the day
### Default: none - This must be specified
cmd: php /code/%day%/run.php --file %input%

### When running docker images, don't use `-it` on the `docker run` command line
### Default: False
# notty: True

### Enable or disable hyperfine for measurement (Default: enabled)
### Default: True
# hyperfine: False

### Enable or disable using a shell for hyperfine runs (Default: disabled)
### Default: True
# hyperfineshell: True

### [%] Environment vars to set on container
### These will exist on every type of container run
### Default: none
environment:
 - TIMED=1

### [%] Path to per-day code. (Directory or File)
### This will be checked to decide if the day exists and needs running, and to check the code version
### If this is a file only changes to that file will trigger a re-run, if it is a directory then any changes to any files within the
### directory will trigger a re-run.
### Default: %day%
daypath: %day%

### Path to any additional common files that should count as changing all days.
### Behaves similar to daypath, any entry in this list can be a file or directory.
### (the .aocbench.yaml file is included in this list by default)
### Default: none
common:
 - common

### [%] Path to per-day input file.
### This is the file that will be overwritten with other test inputs, or used to feed input to other participants
### This is also the path that will be used to generate %inputpath%
### Default: `/input.txt` appended to `daypath`
inputfile: %day%/input.txt

### [%] Path to per-day answer file used to validate other participant answers
### Default: `/answers.txt` appended to `daypath`
answerfile: %day%/answers.txt
```

Options marked with a `[%]` will allow variable replacements:

- `%day%` - The day to run, without zero padding.
- `%zeroday%`/`%dayzero%` - The day to run, with zero padding.
- `%year%` - The year that is being run (for monorepos)
- `%input%` - The input file path if needed (This will be an absolute path) (If the application automatically reads from the `inputfile` location then this is unrequired)
